---
name: CI/CD Django Provisionamento no Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build, Push e Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud e Docker
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          install_components: ['gke-gcloud-auth-plugin', 'beta']

      - name: Configurar Docker para Artifact Registry (GAR)
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Construir e Enviar Imagem
        id: build_push
        run: |
          # URL da Imagem construída com Variáveis do Repositório
          IMAGE_URL="${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}"
          echo "Building and pushing $IMAGE_URL"
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL

          # Salva a URL para o próximo Job
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Deploy no Cloud Run (Serviço principal)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: ${{ vars.REGION }}
          image: ${{ steps.build_push.outputs.image_url }}
          service_account: ${{ vars.SA_RUNTIME_EMAIL }}
          flags: --add-cloudsql-instances ${{ vars.CLOUD_SQL_CONNECTION_NAME }} --service-account=${{ vars.SA_RUNTIME_EMAIL }}
          env_vars: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            PROVISION_API_KEY=${{ secrets.PROVISION_API_KEY }}
            CLOUD_SQL_CONNECTION_NAME=${{ vars.CLOUD_SQL_CONNECTION_NAME }}
            DB_NAME=${{ vars.DB_NAME }}
            IS_CLOUD_RUN=True
            GS_BUCKET_NAME=${{ vars.GS_BUCKET_NAME }}

      - name: Executar Migrations (via gcloud CLI)
        run: |
          # Reusa a URL da imagem que acabamos de construir
          IMAGE_URL="${{ steps.build_push.outputs.image_url }}"
          
          echo "Iniciando Job de Migração..."

          gcloud beta run jobs execute ${{ vars.SERVICE_NAME }}-migrate \
            --region ${{ vars.REGION }} \
            --image $IMAGE_URL \
            --command python \
            --args manage.py,migrate,--noinput \
            --add-cloudsql-instances ${{ vars.CLOUD_SQL_CONNECTION_NAME }} \
            --service-account ${{ vars.SA_RUNTIME_EMAIL }} \
            --set-env-vars SECRET_KEY=${{ secrets.SECRET_KEY }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},MONGODB_URI=${{ secrets.MONGODB_URI }},CLOUD_SQL_CONNECTION_NAME=${{ vars.CLOUD_SQL_CONNECTION_NAME }},DB_NAME=${{ vars.DB_NAME }},IS_CLOUD_RUN=True \
            --wait --quiet
